In [11]:
## Import Dependencies
import pandas as pd
from pathlib import Path
# File to Load
state_and_county = Path("/Users/kelcigriffin/Project1/FoodEnvironmentAtlas/StateAndCountyData.csv")
# Read the modified state_and_county csv and store into Pandas DataFrame
state_and_county_df = pd.read_csv(state_and_county, encoding="utf-8")
state_and_county_df.head()
#Cleaning Data
#Make List for state?
georgia = ["GA"]
# Start by getting the last (greatest) timepoint for each mouse
filter_georgia = state_and_county_df["State"]=="GA"
ga_counties = state_and_county_df.loc[filter_georgia, [ "FIPS", "County", "Variable_Code"]]
unique_ga_counties = ga_counties.drop
ga_counties.value_counts()
ga_counties.reset_index()

        index   FIPS   County          Variable_Code
0       15864  13001  Appling          LACCESS_POP10
1       15865  13001  Appling          LACCESS_POP15
2       15866  13001  Appling  PCH_LACCESS_POP_10_15
3       15867  13001  Appling      PCT_LACCESS_POP10
4       15868  13001  Appling      PCT_LACCESS_POP15
...       ...    ...      ...                    ...
41538  851125     13    Total  State_Population_2014
41539  851126     13    Total  State_Population_2015
41540  851127     13    Total  State_Population_2016
41541  851128     13    Total  State_Population_2017
41542  851129     13    Total  State_Population_2018

[41543 rows x 4 columns]